# Generated by Django 3.1.4 on 2020-12-18 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spm_ck', '0006_auto_20201218_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='customer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
