# Generated by Django 3.1.4 on 2020-12-20 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spm_ck', '0009_auto_20201220_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rated_no',
            field=models.FloatField(blank=True, max_length=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
